export const slogans = [
  "Cada gota de sudor cuenta… Nutre tu esfuerzo.",
  "Haz que cada repetición valga… Nutre tu esfuerzo.",
  "Más fuerza, más resistencia… Nutre tu esfuerzo.",
  "Supera tus límites cada día… Nutre tu esfuerzo.",
  "Resultados que se sienten… Nutre tu esfuerzo.",
  "No te detengas hasta lograrlo… Nutre tu esfuerzo.",
  "Dale a tu cuerpo lo que merece… Nutre tu esfuerzo.",
  "Impulsa tu entrenamiento al máximo… Nutre tu esfuerzo.",
  "Transforma tu esfuerzo en victoria… Nutre tu esfuerzo.",
  "Cada meta alcanzada empieza aquí… Nutre tu esfuerzo.",
  "Para los que no se rinden… Nutre tu esfuerzo.",
  "Cada día más fuerte… Nutre tu esfuerzo.",
  "Haz que cada entrenamiento cuente… Nutre tu esfuerzo.",
  "El poder está en tu constancia… Nutre tu esfuerzo.",
  "Tu cuerpo lo agradecerá… Nutre tu esfuerzo.",
  "Entrena duro, recupera mejor… Nutre tu esfuerzo.",
  "De la motivación a la acción… Nutre tu esfuerzo.",
  "Rompe barreras, alcanza metas… Nutre tu esfuerzo.",
  "Cada desafío es una oportunidad… Nutre tu esfuerzo.",
  "Fuerza, energía y resistencia… Nutre tu esfuerzo.",
  "Esfuerzo constante, resultados visibles… Nutre tu esfuerzo.",
  "No solo entrenes, evoluciona… Nutre tu esfuerzo.",
  "Más energía, más rendimiento… Nutre tu esfuerzo.",
  "Construye tu cuerpo, fortalece tu mente… Nutre tu esfuerzo.",
  "Cada repetición cuenta… Nutre tu esfuerzo.",
  "Para atletas que buscan más… Nutre tu esfuerzo.",
  "Convierte tu sudor en resultados… Nutre tu esfuerzo.",
  "Alcanza tu máximo potencial… Nutre tu esfuerzo.",
  "Cada movimiento importa… Nutre tu esfuerzo.",
  "Tu entrenamiento, tu victoria… Nutre tu esfuerzo.",
  "La constancia paga… Nutre tu esfuerzo.",
  "Rinde más, siente mejor… Nutre tu esfuerzo.",
  "Impulsa tu cuerpo, desafía tus límites… Nutre tu esfuerzo.",
  "Cada día es una oportunidad… Nutre tu esfuerzo.",
  "Alimenta tus músculos, fortalece tu rendimiento… Nutre tu esfuerzo.",
  "No pares hasta estar orgulloso… Nutre tu esfuerzo.",
  "Entrena con propósito… Nutre tu esfuerzo.",
  "De la disciplina viene la fuerza… Nutre tu esfuerzo.",
  "Para los que sueñan en grande… Nutre tu esfuerzo.",
  "Tu cuerpo, tu compromiso… Nutre tu esfuerzo.",
  "Siente la diferencia, vive el progreso… Nutre tu esfuerzo.",
  "Cada esfuerzo cuenta… Nutre tu esfuerzo.",
  "Hazlo por ti, hazlo con fuerza… Nutre tu esfuerzo.",
  "Cambia tu rutina, cambia tu vida… Nutre tu esfuerzo.",
  "El trabajo duro se recompensa… Nutre tu esfuerzo.",
  "Rinde más allá de lo esperado… Nutre tu esfuerzo.",
  "Supera cada límite, conquista cada meta… Nutre tu esfuerzo.",
  "Fuerza interior, resultados visibles… Nutre tu esfuerzo.",
  "Cada gota de esfuerzo tiene recompensa… Nutre tu esfuerzo.",
  "Tu esfuerzo merece lo mejor… Nutre tu esfuerzo."
];
